create table "public"."feeds" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "rss" text
);


alter table "public"."feeds" enable row level security;

CREATE UNIQUE INDEX feeds_pkey ON public.feeds USING btree (id);

alter table "public"."feeds" add constraint "feeds_pkey" PRIMARY KEY using index "feeds_pkey";

grant delete on table "public"."feeds" to "anon";

grant insert on table "public"."feeds" to "anon";

grant references on table "public"."feeds" to "anon";

grant select on table "public"."feeds" to "anon";

grant trigger on table "public"."feeds" to "anon";

grant truncate on table "public"."feeds" to "anon";

grant update on table "public"."feeds" to "anon";

grant delete on table "public"."feeds" to "authenticated";

grant insert on table "public"."feeds" to "authenticated";

grant references on table "public"."feeds" to "authenticated";

grant select on table "public"."feeds" to "authenticated";

grant trigger on table "public"."feeds" to "authenticated";

grant truncate on table "public"."feeds" to "authenticated";

grant update on table "public"."feeds" to "authenticated";

grant delete on table "public"."feeds" to "service_role";

grant insert on table "public"."feeds" to "service_role";

grant references on table "public"."feeds" to "service_role";

grant select on table "public"."feeds" to "service_role";

grant trigger on table "public"."feeds" to "service_role";

grant truncate on table "public"."feeds" to "service_role";

grant update on table "public"."feeds" to "service_role";


