alter table "public"."feeds" drop constraint "feeds_pkey";

drop index if exists "public"."feeds_pkey";

create table "public"."feedMedia" (
    "id" bigint generated by default as identity not null,
    "feed_id" uuid not null,
    "media_id" uuid not null
);


alter table "public"."feedMedia" enable row level security;

create table "public"."media" (
    "id" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone not null default now(),
    "source" text,
    "author" text,
    "title" text,
    "description" text,
    "url" text not null
);


alter table "public"."media" enable row level security;

alter table "public"."feeds" alter column "uuid" set not null;

CREATE UNIQUE INDEX "feedMedia_pkey" ON public."feedMedia" USING btree (id);

CREATE UNIQUE INDEX feeds_uuid_key ON public.feeds USING btree (uuid);

CREATE UNIQUE INDEX media_pkey ON public.media USING btree (id);

CREATE UNIQUE INDEX feeds_pkey ON public.feeds USING btree (id, uuid);

alter table "public"."feedMedia" add constraint "feedMedia_pkey" PRIMARY KEY using index "feedMedia_pkey";

alter table "public"."media" add constraint "media_pkey" PRIMARY KEY using index "media_pkey";

alter table "public"."feeds" add constraint "feeds_pkey" PRIMARY KEY using index "feeds_pkey";

alter table "public"."feedMedia" add constraint "public_feedMedia_feed_id_fkey" FOREIGN KEY (feed_id) REFERENCES feeds(uuid) not valid;

alter table "public"."feedMedia" validate constraint "public_feedMedia_feed_id_fkey";

alter table "public"."feedMedia" add constraint "public_feedMedia_media_id_fkey" FOREIGN KEY (media_id) REFERENCES media(id) not valid;

alter table "public"."feedMedia" validate constraint "public_feedMedia_media_id_fkey";

alter table "public"."feeds" add constraint "feeds_uuid_key" UNIQUE using index "feeds_uuid_key";

grant delete on table "public"."feedMedia" to "anon";

grant insert on table "public"."feedMedia" to "anon";

grant references on table "public"."feedMedia" to "anon";

grant select on table "public"."feedMedia" to "anon";

grant trigger on table "public"."feedMedia" to "anon";

grant truncate on table "public"."feedMedia" to "anon";

grant update on table "public"."feedMedia" to "anon";

grant delete on table "public"."feedMedia" to "authenticated";

grant insert on table "public"."feedMedia" to "authenticated";

grant references on table "public"."feedMedia" to "authenticated";

grant select on table "public"."feedMedia" to "authenticated";

grant trigger on table "public"."feedMedia" to "authenticated";

grant truncate on table "public"."feedMedia" to "authenticated";

grant update on table "public"."feedMedia" to "authenticated";

grant delete on table "public"."feedMedia" to "service_role";

grant insert on table "public"."feedMedia" to "service_role";

grant references on table "public"."feedMedia" to "service_role";

grant select on table "public"."feedMedia" to "service_role";

grant trigger on table "public"."feedMedia" to "service_role";

grant truncate on table "public"."feedMedia" to "service_role";

grant update on table "public"."feedMedia" to "service_role";

grant delete on table "public"."media" to "anon";

grant insert on table "public"."media" to "anon";

grant references on table "public"."media" to "anon";

grant select on table "public"."media" to "anon";

grant trigger on table "public"."media" to "anon";

grant truncate on table "public"."media" to "anon";

grant update on table "public"."media" to "anon";

grant delete on table "public"."media" to "authenticated";

grant insert on table "public"."media" to "authenticated";

grant references on table "public"."media" to "authenticated";

grant select on table "public"."media" to "authenticated";

grant trigger on table "public"."media" to "authenticated";

grant truncate on table "public"."media" to "authenticated";

grant update on table "public"."media" to "authenticated";

grant delete on table "public"."media" to "service_role";

grant insert on table "public"."media" to "service_role";

grant references on table "public"."media" to "service_role";

grant select on table "public"."media" to "service_role";

grant trigger on table "public"."media" to "service_role";

grant truncate on table "public"."media" to "service_role";

grant update on table "public"."media" to "service_role";

create policy "Enable read access for all users"
on "public"."media"
as permissive
for select
to public
using (true);



